name: 'Netlify Deploy'

on:
  release:
    types: [published]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN_SECRET }}
          NETLIFY_SITE_ID: ${{ variables.MY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true