name: 'Netlify Deploy'

on:
  release:
    types: [published]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.11.1"
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
  
  deploy:
    needs: build
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./breadboard-gallery
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN_SECRET }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true